name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: "Build Challenge 1: echo"
        run: go build -v ./cmd/challenge_1_echo
      - name: "Build Challenge 2: unique id generation"
        run: go build -v ./cmd/challenge_2_unique_id_generation
      - name: "Build Challenge 3a: single-node broadcast"
        run: go build -v ./cmd/challenge_3_single_node_broadcast
